#ifndef XROUTERVERSION
#define XROUTERVERSION

#define XROUTER_VERSION_MAJOR 0
#define XROUTER_VERSION_MINOR 1
#define XROUTER_VERSION_DESCR "xrouter"

#define MAKE_VERSION(major,minor) (( major << 16 ) + minor )
#define XROUTER_VERSION MAKE_VERSION(XROUTER_VERSION_MAJOR, XROUTER_VERSION_MINOR)

#define XROUTER_PROTOCOL_VERSION 0xff000023

#endif // XROUTERVERSION
